version: '3'
services:
  nginx:
    build: requirements/nginx/.
    restart: always
    image: nginx
    container_name: "nginx_container"
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inceptionNetwork
  maria-db:
    build: requirements/mariadb/.
    restart: always
    image: maria-db
    container_name: "mariaDB_container"
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inceptionNetwork
  wordpress:
    build: requirements/wordpress/.
    restart: always
    depends_on:
      - maria-db
    volumes:
      - wp:/var/www/wordpress
    image: wordpress
    container_name: "wordpress_container"
    env_file:
      - .env
    networks:
      - inceptionNetwork
  static-site:
      build: requirements/bonus/staticSite/.
      restart: always
      container_name: "static-site_container"
      image: static-site
      ports:
         - "90:90"

volumes:
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/klaarous/data/wp/
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/klaarous/data/db/

networks:
  inceptionNetwork:
